### ISSUE TITLE
Initial time is set to currentTime for timeSelector

### ISSUE THREAD

**Issue by freekvandeven** [Iconica-Development/flutter_input_library#18]
When using the inputType .time or dateTime the Time selection will always start at the initialTime: TimeOfDay.now()
There is no option to set this time.

the issue is in src/inputs/date_picker/date_picker_field.dart:149

**Comment by Gorter-dev** [comment]
This seems to be already resolved

![Image](https://github.com/Iconica-Development/flutter_input_library/assets/52274327/ee727498-66b7-4986-9588-74a80dc2b756)
